### PR TITLE
Added possibility to upload user profile image. Added profile image v…

### PR DESCRIPTION
**Pull request by Ravennod**
…alidation.

### CODE REVIEW

**Comment by Ravennod** [comment]
feature_image_1
feature_image_2

**Comment by Ravennod** [comment]
To make this feature work please replace file MultipartDataMediaFormatter.dll at MedicalDocManagment.WebUI\bin with https://www.codeproject.com/KB/aspnet/652633/MultipartDataMediaFormatter_bin_1.0.2.zip. Because NuGet version is outdated.

**Review by KostetskyiYaroslav — APPROVED** [review]

**Comment by AndriiKatsubo** [comment]
Form resets if image is incorrect — I think that this behaviour should be changed.

**Review by AndriiKatsubo — DISMISSED** [review]
Changes were requested according to comment.

**Comment by Ravennod** [comment]
Form resets when submitted, whether image is valid or not. This behaviour can't be changed, because current strategy is to upload image with all other form data.

**Comment by AndriiKatsubo** [comment]
I think that this is wrong, because user have to input data again.

**Review by AndriiKatsubo — APPROVED** [review]

**Comment by AndriiKatsubo** [comment]
Consider adding content of `Files` directory to `gitignore`.

**Pull request merged**
