### PR TITLE
improved feature\'s work

### PR DESCRIPTION
**Pull request by KostetskyiYaroslav**

### CODE REVIEW

**Comment by AndriiKatsubo** [comment]
default
Changing values of form's fields causes immediate changes in list of users — I don't think that this is proper behaviour of edit form.

**Review by AndriiKatsubo — DISMISSED** [review]
Changes were requested according to comment.

**Comment by KostetskyiYaroslav** [comment]
Probably, you're right.
OK, I'll change form's behaviour

**Review by Ravennod — APPROVED** [review]

**Comment by AndriiKatsubo** [comment]
default
Feature doesn't work from search user results.

**Review by AndriiKatsubo — CHANGES_REQUESTED** [review]
Changes according to comment were requested.

**Pull request closed without merging**
