### PR TITLE
Fixed horizontal scrollbar. Changed the way form resets. Removed cons…

### PR DESCRIPTION
**Pull request by Ravennod**
…ole output.

### CODE REVIEW

**Comment by AndriiKatsubo** [comment]
There is still some output in console when image is not valid.
default

**Review by AndriiKatsubo — DISMISSED** [review]
Changes were requested according to comment message.

**Comment by Ravennod** [comment]
But we were talking about removing console output in case of successful result, with leaving messages about errors untouched.

**Comment by AndriiKatsubo** [comment]
> But we were talking about removing console output in case of successful result, with leaving messages about errors untouched.

We weren't talking about leaving messages about errors untouched. But if you don't want to change this, then I'll approve this pull request.

**Review by AndriiKatsubo — APPROVED** [review]

**Review by KostetskyiYaroslav — APPROVED** [review]

**Pull request merged**
