### PR TITLE
Feature/visit

### PR DESCRIPTION
**Pull request by KostetskyiYaroslav**
-implemented possibility to add summary as a new visit to the doctor
-added possibility to view patient's visits on separate page

### CODE REVIEW

**Comment by AndriiKatsubo** [comment]
Shouldn't field with date be narrower? Date is not so wide to take all width of modal window.
default

**Comment by AndriiKatsubo** [comment]
Multiline summaries are displayed in one line. I think that this is a bug.
default

**Review by AndriiKatsubo — DISMISSED** [review]
Question was asked and change was requested according to comment message.

**Comment by KostetskyiYaroslav** [comment]
It isn't a bug. Because summary is just a plain text. But it's a great idea. 
> Multiline summaries are displayed in one line. I think that this is a bug.

**Review by AndriiKatsubo — APPROVED** [review]

**Review by Ravennod — APPROVED** [review]

**Pull request merged**
